name: Docker CI - Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Buildx (cache)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Image build
      - name: Build and Test (inside Docker)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false # Avoid upload to Docker Hub
          load: true # Bring image to local Docker
          tags: cabgen-backend:test
          # GitHub smart cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
